#!/usr/bin/env bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd "$DIR"

echo "=== [1/3] Derleniyor: Swift Release ==="
swift build -c release

echo "=== [2/3] Paketleniyor: pomo.app ==="
APP_BUNDLE="build/pomo.app"
rm -rf "$APP_BUNDLE"
mkdir -p "$APP_BUNDLE/Contents/MacOS"
mkdir -p "$APP_BUNDLE/Contents/Resources"

# Copy binary
cp ".build/release/pomo" "$APP_BUNDLE/Contents/MacOS/pomo"

# Copy Info.plist
cp "Resources/Info.plist" "$APP_BUNDLE/Contents/Info.plist"

# Copy AppIcon
if [ -f "Resources/AppIcon.icns" ]; then
    cp "Resources/AppIcon.icns" "$APP_BUNDLE/Contents/Resources/AppIcon.icns"
fi

# Copy resource bundles if generated by SPM
if [ -d ".build/release/Pomo_PomoCore.bundle" ]; then
    cp -R ".build/release/Pomo_PomoCore.bundle" "$APP_BUNDLE/Contents/Resources/"
fi

echo "=== [3/3] İmzalanıyor: Ad-hoc Codesign ==="
codesign --force --deep --sign - "$APP_BUNDLE"

echo "Tamamlandı: $APP_BUNDLE oluşturuldu!"
